- name: install web component
  hosts: localhost
  become: yes
  tasks:
  - name: install web component
    ansible.builtin.dnf:
      name: nginx 
      state: present

  - name: start and enable nginx
    ansible.builtin.service:
      name: nginx
      state: restarted
      enabled: yes
  
  